version: '3.9'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-be-dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # command: npm run start:dev
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild

  postgres:
    image: postgres:16-alpine
    container_name: book-postgres-dev
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: book-redis-dev
    restart: always
    ports:
      - '6379:6379'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: book-pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
